#!/usr/bin/env bash
# a Bash script that transfers a file from our client to a server

argv=("$@")
if (( $#<=3 )); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

PATH_TO_FILE=${argv[0]}
IP=${argv[1]}
USERNAME=${argv[2]}
PATH_TO_SSH_KEY=${argv[3]}
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~
