#!/usr/bin/env bash
# Install Nginx on the server and configure it to return "Hello World!" at the root

sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
