#!/usr/bin/env bash
# Install Nginx on the server and configure it to redirect "/redirect_me" to another page

sudo apt update -y
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '/^server {/a \    location \/redirect_me {\n        return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default
# Restart Nginx service
sudo service nginx restart
