#!/usr/bin/env bash
# This script is displaying "Best School" 8 times using while loops
# It displays "bad luck" at 4th iteration, and "good luck" at 8th iteration

i=0
while (( i < 10 ))
do
	if (( i == 3 ))
	then
		echo "bad luck"
	elif (( i == 7))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done