#!/usr/bin/env bash
# Configures an Ubuntu server with these requirements:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
if  ! grep -q "8.8.8.8 facebook.com" ~/hosts.new
then
    echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi
sed -E -i 's/([0-9]{1,3}\.){3}[0-9]{1,3}[[:space:]]+localhost$/127.0.0.2 localhost/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts